'use client'
import { Button } from '@mui/material'
import React from 'react'



const InterShipDetails = () => {
       
    return (
        <>
           
            <h1 className='text-2xl font-bold'>Title</h1>
            <section className='overflow-y-auto h-[70vh] mt-4'>

                <p className='font-[poppins] leading-9'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, neque esse corporis at necessitatibus quod excepturi cum quaerat modi illo.lore
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt omnis ad doloribus culpa reiciendis totam? Optio, aut facere harum officia ipsum, voluptatem nemo vero eius, veritatis culpa sapiente dolores! Tempore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci natus exercitationem esse tempore provident eos, eius quia tempora obcaecati laudantium mollitia molestias voluptas neque. Rem fugiat eos maiores neque fugit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse harum officiis explicabo, architecto porro nihil enim ut laudantium assumenda veritatis ratione pariatur nulla id! Praesentium vero quae et dolores debitis. lorem 10
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni accusamus officiis ad quis, dolore, atque laboriosam praesentium fuga suscipit, ne

                </p>

            </section>
            <Button variant='contained' color='primary' className='leading-6 mt-4' >EDIT</Button>


           
        </>
    )
}

export default InterShipDetails