import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient } from "@tanstack/react-query";
import NavBar from "@/components/common/NavBar";
import SideBar from "@/components/common/SideBar";
import QueryProvider from "@/tanstack/TanstackProvider";


const queryClient = new QueryClient();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div>
            <NavBar />
            {/* <SideBar/> */}
          </div>
          <div className="flex h-[70vh] gap-4 ">
            {/* Sidebar */}
            <div className="w-[15%] ">
              <SideBar />
            </div>
            <div className="w-[85%] xl:ml-4 md:ml-[10%] sm:ml-[20%] ml-[25%]">
              {children}
            </div>


          </div>
          {/* {children} */}

        </body>
      </QueryProvider>
    </html>
  );
}
